baseURL = "https://dodonium.github.io/hugo_test/"
languageCode = "ja-jp"
title = "Torigoya" 
theme = ["custom","book"]



[params]
  BookTheme = 'light'
  BookSection = '*'
  BookSearch = false
  BookToC = false